from typing import List
from .champions import Champion
from .traits import Trait

class Solution:
    @property
    def champions(self) -> List[str]: ...
    @property
    def missing_champions(self) -> List[str]: ...
    @property
    def traits(self) -> List[str]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

