from enum import Enum

class Trait(Enum):
    Ascendant = ...
    Bastion = ...
    BatQueen = ...
    BestFriends = ...
    Blaster = ...
    Hunter = ...
    Incantor = ...
    Mage = ...
    Multistriker = ...
    Preserver = ...
    Scholar = ...
    Shapeshifter = ...
    Vanguard = ...
    Warrior = ...
    Arcana = ...
    Chrono = ...
    Dragon = ...
    Druid = ...
    Eldritch = ...
    Faerie = ...
    Frost = ...
    Honeymancy = ...
    Portal = ...
    Pyro = ...
    Ravenous = ...
    Sugarcraft = ...
    Witchcraft = ...

class ActiveTrait:
    @property
    def trait_(self) -> Trait: ...
    @property
    def level(self) -> int: ...

